apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-todo: secret/dev/redis
        vault.hashicorp.com/agent-inject-status: update
        vault.hashicorp.com/agent-inject-template-todo: |
          {{`{{- with secret "secret/dev/redis" -}}`}}
            export SPRING_DATA_REDIS_PASSWORD={{`{{ .Data.data.password }}`}}
            export SPRING_DATA_REDIS_HOST={{`{{ .Data.data.host }}`}}
            export SPRING_DATA_REDIS_PORT={{`{{ .Data.data.port }}`}}
          {{`{{- end }}`}}
        vault.hashicorp.com/namespace: todo
        vault.hashicorp.com/role: todo
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: actuator
              containerPort: 18080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.management.port }}
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.management.port }}
            initialDelaySeconds: 60
            periodSeconds: 3
          command: ['/bin/sh', '-c']
          args: ['source /vault/secrets/todo && java -jar app.jar']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
