apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.management.port }}
      targetPort: {{ .Values.management.port }}
      protocol: TCP
      name: management
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
