apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-configmap
data:
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "todo"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "destination" = "/vault/secrets/application-vault.properties"
      "contents" = <<EOT
      "{{- with secret "secret/dev/redis" -}}
      spring.data.redis.host={{ .Data.data.password }}
      spring.data.redis.password={{`{{ .Data.data.password }}`}}
      spring.data.redis.port={{`{{ .Data.data.port }}`}}
      {{- end }}"
      EOT
    }
  