apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-configmap
data:
  config-init.hcl: |
    "auto_auth" = {
      "method" = {
        "config" = {
          "role" = "todo"
        }
        "type" = "kubernetes"
      }

      "sink" = {
        "config" = {
          "path" = "/home/vault/.token"
        }

        "type" = "file"
      }
    }

    "exit_after_auth" = true
    "pid_file" = "/home/vault/.pid"

    "template" = {
      "destination" = "/vault/secrets/todo"
      "contents" = <<EOT
      {{`{{- with secret "secret/dev/redis" -}}`}}
      export SPRING_DATA_REDIS_PASSWORD={{`{{ .Data.data.password }}`}}
      export SPRING_DATA_REDIS_HOST={{`{{ .Data.data.host }}`}}
      export SPRING_DATA_REDIS_PORT={{`{{ .Data.data.port }}`}}
      {{`{{- end }}`}}
      EOT
    }
  