apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todo
  template:
    metadata:
      labels:
        name: todo
    spec:
      containers:
        - name: todo-server
          image: registry.digitalocean.com/cant-code-registry/todo:latest
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: hostname
              value: redis-13019.c305.ap-south-1-1.ec2.cloud.redislabs.com
            - name: port
              value: '13019'