apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  labels:
    name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: todo
  template:
    metadata:
      labels:
        name: todo
    spec:
      containers:
        - name: todo-server
          image: registry.digitalocean.com/cant-code-registry/todo:latest
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 300m
              memory: 256Mi
          ports:
            - containerPort: 8080