name: Build and Verify change

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    uses: cant-code/github-workflows/.github/workflows/java-spring-workflow.yml@main
    name: Build and verify
    with:
      SONAR_PROJECT_KEY: cant-code_todo-server
      ARTIFACT_NAME: todo
      ARTIFACT_PATH: target/overengineered*.jar
    secrets: inherit