name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    uses: cant-code/github-workflows/.github/workflows/java-spring-workflow.yml@main
    name: Build and verify
    with:
      SONAR_PROJECT_KEY: cant-code_todo-server
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  create-image:
    name: Build Image and Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
          path: target

      - name: Display Structure
        run: ls -R
        working-directory: target

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: damnationcantcode/todo-backend:latest